@contentType = application/json
@baseUrl = http://localhost:4001

###
# @name ping
GET {{baseUrl}}/ping
Content-Type:  {{contentType}}

###

# @name test-get
GET {{baseUrl}}/my-testing-path?foo=bar&bar=foo
Content-Type:  {{contentType}}

###
# @name test-post
POST {{baseUrl}}/my-testing-path
Content-Type:  {{contentType}}

{"foo":"bar"}

###
# @name test-put
PUT {{baseUrl}}/my-testing-path
Content-Type:  {{contentType}}

{"bar":"foo"}

###
# @name test-delete
DELETE {{baseUrl}}/my-testing-path?id=foo&action=bar
Content-Type:  {{contentType}}

###

# @name stats
GET {{baseUrl}}/stats
Content-Type:  {{contentType}}

###


@method=POST,GET
@limit=20
@offset=10
@order=DESC
@path=my-testing-path
@matchPath=false
@from=2023-04-01
@to=2023-04-17

# @name requests
GET {{baseUrl}}/requests?method={{method}}&limit={{limit}}&offset={{offset}}&order={{order}}&path={{path}}&matchPath={{matchPath}}&from={{from}}&to={{to}}
Content-Type:  {{contentType}}

###

# @name request
GET {{baseUrl}}/request/lgkyhqjx
Content-Type:  {{contentType}}

###

# @name response
POST {{baseUrl}}/response
Content-Type:  {{contentType}}

{
    "result": {
        "msg": "SUCCESS"
    }
}
###